<a href="https://colab.research.google.com/github/KadamShivanjalii/OIBSIP_DataScience_Task1/blob/main/ProblemStatementNo_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=sns.load_dataset('titanic')
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [3]:
df.isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [4]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
df.isnull().sum().sum()

np.int64(869)

In [6]:
df.shape

(891, 15)

In [7]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [8]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [10]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [15]:
df1=pd.get_dummies(df,columns=['sex','embarked','who'])
df1.head(30)

,survived,pclass,age,sibsp,parch,fare,class,adult_male,deck,embark_town,alive,alone,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,who_child,who_man,who_woman
0,0,3,22.0,1,0,7.2500,Third,True,NaN,Southampton,no,False,False,True,False,False,True,False,True,False
1,1,1,38.0,1,0,71.2833,First,False,C,Cherbourg,yes,False,True,False,True,False,False,False,False,True
2,1,3,26.0,0,0,7.9250,Third,False,NaN,Southampton,yes,True,True,False,False,False,True,False,False,True
3,1,1,35.0,1,0,53.1000,First,False,C,Southampton,yes,False,True,False,False,False,True,False,False,True
4,0,3,35.0,0,0,8.0500,Third,True,NaN,Southampton,no,True,False,True,False,False,True,False,True,False
5,0,3,NaN,0,0,8.4583,Third,True,NaN,Queenstown,no,True,False,True,False,True,False,False,True,False
6,0,1,54.0,0,0,51.8625,First,True,E,Southampton,no,True,False,True,False,False,True,False,True,False
7,0,3,2.0,3,1,21.0750,Third,False,NaN,Southampton,no,False,False,True,False,False,True,True,False,False
8,1,3,27.0,0,2,11.1333,Third,False,NaN,Southampton,yes,False,True,False,False,False,True,False,False,True
9,1,2,14.0,1,0,30.0708,Second,False,NaN,Cherbourg,yes,False,True,False,True,False,False,True,False,False
10,1,3,4.0,1,1,16.7000,Third,False,G,Southampton,yes,False,True,False,False,False,True,True,False,False
11,1,1,58.0,0,0,26.5500,First,False,C,Southampton,yes,True,True,False,False,False,True,False,False,True
12,0,3,20.0,0,0,8.0500,Third,True,NaN,Southampton,no,True,False,True,False,False,True,False,True,False
13,0,3,39.0,1,5,31.2750,Third,True,NaN,Southampton,no,False,False,True,False,False,True,False,True,False
14,0,3,14.0,0,0,7.8542,Third,False,NaN,Southampton,no,True,True,False,False,False,True,True,False,False
15,1,2,55.0,0,0,16.0000,Second,False,NaN,Southampton,yes,True,True,False,False,False,True,False,False,True
16,0,3,2.0,4,1,29.1250,Third,False,NaN,Queenstown,no,False,False,True,False,True,False,True,False,False
17,1,2,NaN,0,0,13.0000,Second,True,NaN,Southampton,yes,True,False,True,False,False,True,False,True,False
18,0,3,31.0,1,0,18.0000,Third,False,NaN,Southampton,no,False,True,False,False,False,True,False,False,True
19,1,3,NaN,0,0,7.2250,Third,False,NaN,Cherbourg,yes,True,True,False,True,False,False,False,False,True
20,0,2,35.0,0,0,26.0000,Second,True,NaN,Southampton,no,True,False,True,False,False,True,False,True,False
21,1,2,34.0,0,0,13.0000,Second,True,D,Southampton,yes,True,False,True,False,False,True,False,True,False
22,1,3,15.0,0,0,8.0292,Third,False,NaN,Queenstown,yes,True,True,False,False,True,False,True,False,False
23,1,1,28.0,0,0,35.5000,First,True,A,Southampton,yes,True,False,True,False,False,True,False,True,False
24,0,3,8.0,3,1,21.0750,Third,False,NaN,Southampton,no,False,True,False,False,False,True,True,False,False
25,1,3,38.0,1,5,31.3875,Third,False,NaN,Southampton,yes,False,True,False,False,False,True,False,False,True
26,0,3,NaN,0,0,7.2250,Third,True,NaN,Cherbourg,no,True,False,True,True,False,False,False,True,False
27,0,1,19.0,3,2,263.0000,First,True,C,Southampton,no,False,False,True,False,False,True,False,True,False
28,1,3,NaN,0,0,7.8792,Third,False,NaN,Queenstown,yes,True,True,False,False,True,False,False,False,True
29,0,3,NaN,0,0,7.8958,Third,True,NaN,Southampton,no,True,False,True,False,False,True,False,True,False

In [16]:
df.select_dtypes(include=['object','category']).columns

Index(['sex', 'embarked', 'class', 'who', 'deck', 'embark_town', 'alive'], dtype='object')

In [17]:
df.select_dtypes(include=['object','category']).columns

Index(['sex', 'embarked', 'class', 'who', 'deck', 'embark_town', 'alive'], dtype='object')

In [20]:
df.fillna(df.mean(numeric_only=True))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [21]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [22]:
df.fillna(df.mode())

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [23]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [25]:
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

In [26]:
df['deck']=df['deck'].fillna(df['deck'].mode()[0])

In [27]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck             0
embark_town      2
alive            0
alone            0
dtype: int64

In [28]:
df['age']=df['age'].fillna(df['age'].mode()[0])

In [29]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    2
alive          0
alone          0
dtype: int64

In [30]:
df['embark_town']=df['embark_town'].fillna(df['embark_town'].mode()[0])

In [31]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [33]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['sex_le']=le.fit_transform(df['sex'])

In [34]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_le
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,C,Southampton,no,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,C,Southampton,no,True,1
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0
888,0,3,female,24.0,1,2,23.4500,S,Third,woman,False,C,Southampton,no,False,0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,C,Queenstown,no,True,1

In [35]:
df1

,survived,pclass,age,sibsp,parch,fare,class,adult_male,deck,embark_town,alive,alone,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,who_child,who_man,who_woman
0,0,3,22.0,1,0,7.2500,Third,True,NaN,Southampton,no,False,False,True,False,False,True,False,True,False
1,1,1,38.0,1,0,71.2833,First,False,C,Cherbourg,yes,False,True,False,True,False,False,False,False,True
2,1,3,26.0,0,0,7.9250,Third,False,NaN,Southampton,yes,True,True,False,False,False,True,False,False,True
3,1,1,35.0,1,0,53.1000,First,False,C,Southampton,yes,False,True,False,False,False,True,False,False,True
4,0,3,35.0,0,0,8.0500,Third,True,NaN,Southampton,no,True,False,True,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,Second,True,NaN,Southampton,no,True,False,True,False,False,True,False,True,False
887,1,1,19.0,0,0,30.0000,First,False,B,Southampton,yes,True,True,False,False,False,True,False,False,True
888,0,3,NaN,1,2,23.4500,Third,False,NaN,Southampton,no,False,True,False,False,False,True,False,False,True
889,1,1,26.0,0,0,30.0000,First,True,C,Cherbourg,yes,True,False,True,True,False,False,False,True,False
890,0,3,32.0,0,0,7.7500,Third,True,NaN,Queenstown,no,True,False,True,False,True,False,False,True,False